name: ci
on:
  push: { branches: ["main"] }
  pull_request:
jobs:
  build-test-scan-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - run: pip install -r app/requirements.txt pytest
      - run: pytest -q
      - name: Build image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/devops-mini:${{ github.sha }} .
      - name: Trivy scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/devops-mini:${{ github.sha }}
          exit-code: "1"
          ignore-unfixed: true
        continue-on-error: true   # для старта; потом снимите
      - name: Login & push
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/devops-mini:${{ github.sha }}
          docker tag  ${{ secrets.DOCKERHUB_USERNAME }}/devops-mini:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/devops-mini:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/devops-mini:latest
  deploy:
    needs: build-test-scan-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible
      - name: SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Ansible Galaxy deps
        run: ansible-galaxy collection install community.docker
      - name: Deploy
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          GITHUB_SHA: ${{ github.sha }}
        run: ansible-playbook -i ansible/inventory.ini ansible/playbook.yml

